// <auto-generated />
namespace Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AuditDates_RemovedDatabaseGeneratedOption : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AuditDates_RemovedDatabaseGeneratedOption));
        
        string IMigrationMetadata.Id
        {
            get { return "201907231700157_AuditDates_RemovedDatabaseGeneratedOption"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
